import type { Gift, Message } from '@/lib/db/schema'

const createdAt = new Date('2026-07-20T15:00:00.000Z')

export const demoGifts: Gift[] = [
  {
    id: 1,
    name: 'Jogo de panelas antiaderente',
    room: 'Cozinha',
    tier: 'especial',
    note: 'Pode ser em tons neutros.',
    price: '289.90',
    url: 'https://example.com',
    sortOrder: 10,
    claimedBy: null,
    claimedAt: null,
    createdAt,
  },
  {
    id: 2,
    name: 'Kit de potes herméticos',
    room: 'Cozinha',
    tier: 'essencial',
    note: null,
    price: '79.90',
    url: 'https://example.com',
    sortOrder: 20,
    claimedBy: null,
    claimedAt: null,
    createdAt,
  },
  {
    id: 3,
    name: 'Jogo de toalhas de banho',
    room: 'Banheiro',
    tier: 'essencial',
    note: 'Branco, bege ou verde sálvia.',
    price: '119.90',
    url: 'https://example.com',
    sortOrder: 30,
    claimedBy: 'Tia Márcia',
    claimedAt: createdAt,
    createdAt,
  },
  {
    id: 4,
    name: 'Almofadas para o sofá',
    room: 'Sala',
    tier: 'essencial',
    note: null,
    price: '49.90',
    url: 'https://example.com',
    sortOrder: 40,
    claimedBy: null,
    claimedAt: null,
    createdAt,
  },
  {
    id: 5,
    name: 'Jogo de cama casal',
    room: 'Quarto',
    tier: 'especial',
    note: 'Tamanho queen.',
    price: '189.90',
    url: 'https://example.com',
    sortOrder: 50,
    claimedBy: null,
    claimedAt: null,
    createdAt,
  },
  {
    id: 6,
    name: 'Cesto organizador',
    room: 'Organização',
    tier: 'essencial',
    note: null,
    price: '39.90',
    url: null,
    sortOrder: 60,
    claimedBy: null,
    claimedAt: null,
    createdAt,
  },
]

export const demoMessages: Message[] = [
  {
    id: 1,
    giftId: null,
    guestName: 'Carol e Pedro',
    body: 'Que seu novo lar seja cenário de muitos domingos felizes, café passado e risadas!',
    createdAt,
  },
  {
    id: 2,
    giftId: null,
    guestName: 'Tia Márcia',
    body: 'Muita luz, amor e comida boa nessa casa nova. Estou muito feliz por você!',
    createdAt,
  },
]
